
/*
 Copyright (c) 2011 Sencha Inc. - Author: Nicolas Garcia Belmonte (http://philogb.github.com/)

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.

 */

(function(){window.$jit=function(a){var a=a||window,b;for(b in $jit)$jit[b].$extend&&(a[b]=$jit[b])};$jit.version="2.0.1";var f=function(a){return document.getElementById(a)};f.empty=function(){};f.extend=function(a,b){for(var c in b||{})a[c]=b[c];return a};f.lambda=function(a){return"function"==typeof a?a:function(){return a}};f.time=Date.now||function(){return+new Date};f.splat=function(a){var b=f.type(a);return b?"array"!=b?[a]:a:[]};f.type=function(a){var b=f.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
    return"object"!=b?b:a&&a.$$family?a.$$family:a&&a.nodeName&&1==a.nodeType?"element":b};f.type.s=Object.prototype.toString;f.each=function(a,b){if("object"==f.type(a))for(var c in a)b(a[c],c);else{c=0;for(var d=a.length;c<d;c++)b(a[c],c)}};f.indexOf=function(a,b){if(Array.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};f.map=function(a,b){var c=[];f.each(a,function(a,e){c.push(b(a,e))});return c};f.reduce=function(a,b,c){var d=a.length;if(0==d)return c;for(var e=
    3==arguments.length?c:a[--d];d--;)e=b(e,a[d]);return e};f.merge=function(){for(var a={},b=0,c=arguments.length;b<c;b++){var d=arguments[b];if("object"==f.type(d))for(var e in d){var g=d[e],h=a[e];a[e]=h&&"object"==f.type(g)&&"object"==f.type(h)?f.merge(h,g):f.unlink(g)}}return a};f.unlink=function(a){var b;switch(f.type(a)){case "object":b={};for(var c in a)b[c]=f.unlink(a[c]);break;case "array":b=[];c=0;for(var d=a.length;c<d;c++)b[c]=f.unlink(a[c]);break;default:return a}return b};f.zip=function(){if(0===
    arguments.length)return[];for(var a=0,b=[],c=arguments.length,d=arguments[0].length;a<d;a++){for(var e=0,g=[];e<c;e++)g.push(arguments[e][a]);b.push(g)}return b};f.rgbToHex=function(a,b){if(3>a.length)return null;if(4==a.length&&0==a[3]&&!b)return"transparent";for(var c=[],d=0;3>d;d++){var e=(a[d]-0).toString(16);c.push(1==e.length?"0"+e:e)}return b?c:"#"+c.join("")};f.hexToRgb=function(a){if(7!=a.length){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(3!=a.length)return null;for(var b=
    [],c=0;3>c;c++){var d=a[c];1==d.length&&(d+=d);b.push(parseInt(d,16))}return b}a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]};f.destroy=function(a){f.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};f.clean=function(a){for(var a=a.childNodes,b=0,c=a.length;b<c;b++)f.destroy(a[b])};f.addEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};f.addEvents=function(a,b){for(var c in b)f.addEvent(a,c,b[c])};f.hasClass=
    function(a,b){return-1<(" "+a.className+" ").indexOf(" "+b+" ")};f.addClass=function(a,b){f.hasClass(a,b)||(a.className=a.className+" "+b)};f.removeClass=function(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(?:\\s|$)"),"$1")};f.getPos=function(a){for(var b=a,c=0,d=0;b&&!/^(?:body|html)$/i.test(b.tagName);)c+=b.offsetLeft,d+=b.offsetTop,b=b.offsetParent;for(var e=b=0;a&&!/^(?:body|html)$/i.test(a.tagName);)b+=a.scrollLeft,e+=a.scrollTop,a=a.parentNode;return{x:c-b,y:d-e}};f.event={get:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   b){b=b||window;return a||b.event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return 3==a.which||2==a.button},getPos:function(a,b){var b=b||window,a=a||b.event,c=b.document,c=c.documentElement||c.body;a.touches&&a.touches.length&&(a=a.touches[0]);return{x:a.pageX||a.clientX+c.scrollLeft,y:a.pageY||a.clientY+c.scrollTop}},stop:function(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=
    !1}};$jit.util=$jit.id=f;var k=function(a){var a=a||{},b=function(){for(var a in this)"function"!=typeof this[a]&&(this[a]=f.unlink(this[a]));this.constructor=b;if(k.prototyping)return this;a=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return a},c;for(c in k.Mutators)a[c]&&(a=k.Mutators[c](a,a[c]),delete a[c]);f.extend(b,this);b.constructor=k;b.prototype=a;return b};k.Mutators={Implements:function(a,b){f.each(f.splat(b),function(b){k.prototyping=b;var b="function"==
    typeof b?new b:b,d;for(d in b)d in a||(a[d]=b[d]);delete k.prototyping});return a}};f.extend(k,{inherit:function(a,b){for(var c in b){var d=b[c],e=a[c],g=f.type(d);e&&"function"==g?d!=e&&k.override(a,c,d):a[c]="object"==g?f.merge(e,d):d}return a},override:function(a,b,c){var d=k.prototyping;d&&a[b]!=d[b]&&(d=null);a[b]=function(){var e=this.parent;this.parent=d?d[b]:a[b];var g=c.apply(this,arguments);this.parent=e;return g}}});k.prototype.implement=function(){var a=this.prototype;f.each(Array.prototype.slice.call(arguments||
    []),function(b){k.inherit(a,b)});return this};$jit.Class=k;$jit.json={prune:function(a,b){this.each(a,function(a,d){d==b&&a.children&&(delete a.children,a.children=[])})},getParent:function(a,b){if(a.id==b)return!1;var c=a.children;if(c&&0<c.length)for(var d=0;d<c.length;d++){if(c[d].id==b)return a;var e=this.getParent(c[d],b);if(e)return e}return!1},getSubtree:function(a,b){if(a.id==b)return a;for(var c=0,d=a.children;d&&c<d.length;c++){var e=this.getSubtree(d[c],b);if(null!=e)return e}return null},
    eachLevel:function(a,b,c,d){if(b<=c&&(d(a,b),a.children))for(var e=0,a=a.children;e<a.length;e++)this.eachLevel(a[e],b+1,c,d)},each:function(a,b){this.eachLevel(a,0,Number.MAX_VALUE,b)}};$jit.Trans={$extend:!0,linear:function(a){return a}};var x=$jit.Trans,H=function(a,b){b=f.splat(b);return f.extend(a,{easeIn:function(c){return a(c,b)},easeOut:function(c){return 1-a(1-c,b)},easeInOut:function(c){return 0.5>=c?a(2*c,b)/2:(2-a(2*(1-c),b))/2}})};f.each({Pow:function(a,b){return Math.pow(a,b[0]||6)},
    Expo:function(a){return Math.pow(2,8*(a-1))},Circ:function(a){return 1-Math.sin(Math.acos(a))},Sine:function(a){return 1-Math.sin((1-a)*Math.PI/2)},Back:function(a,b){b=b[0]||1.618;return Math.pow(a,2)*((b+1)*a-b)},Bounce:function(a){for(var b,c=0,d=1;;c+=d,d/=2)if(a>=(7-4*c)/11){b=d*d-Math.pow((11-6*c-11*a)/4,2);break}return b},Elastic:function(a,b){return Math.pow(2,10*--a)*Math.cos(20*a*Math.PI*(b[0]||1)/3)}},function(a,b){x[b]=H(a)});f.each(["Quad","Cubic","Quart","Quint"],function(a,b){x[a]=
    H(function(a){return Math.pow(a,[b+2])})});var I=new k({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=f.merge({duration:2500,fps:40,transition:x.Quart.easeInOut,compute:f.empty,complete:f.empty,link:"ignore"},a||{});return this},step:function(){var a=f.time(),b=this.opt;a<this.time+b.duration?(a=b.transition((a-this.time)/b.duration),b.compute(a)):(this.timer=clearInterval(this.timer),b.compute(1),b.complete())},start:function(){if(!this.check())return this;this.time=
    0;this.startTimer();return this},startTimer:function(){var a=this,b=this.opt.fps;if(this.timer)return!1;this.time=f.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/b));return!0},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return!1;this.time=f.time()-this.time;this.timer=clearInterval(this.timer);return!0},check:function(){return!this.timer?!0:"cancel"==this.opt.link?(this.stopTimer(),
    !0):!1}}),r=function(){for(var a=arguments,b=0,c=a.length,d={};b<c;b++){var e=r[a[b]];e.$extend?f.extend(d,e):d[a[b]]=e}return d};r.Canvas={$extend:!0,injectInto:"id",type:"2D",width:!1,height:!1,useCanvas:!1,withLabels:!0,background:!1,Scene:{Lighting:{enable:!1,ambient:[1,1,1],directional:{direction:{x:-100,y:-100,z:-100},color:[0.5,0.3,0.1]}}}};r.Node={$extend:!1,overridable:!1,type:"circle",color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:!1,autoWidth:!1,lineWidth:1,transform:!0,align:"center",
    angularWidth:1,span:1,CanvasStyles:{}};r.Edge={$extend:!1,overridable:!1,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};r.Fx={$extend:!0,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:!0};r.Label={$extend:!1,overridable:!1,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};r.Tips={$extend:!1,enable:!1,type:"auto",offsetX:20,offsetY:20,force:!1,onShow:f.empty,onHide:f.empty};r.NodeStyles=
{$extend:!1,enable:!1,type:"auto",stylesHover:!1,stylesClick:!1};r.Events={$extend:!1,enable:!1,enableForEdges:!1,type:"auto",onClick:f.empty,onRightClick:f.empty,onMouseMove:f.empty,onMouseEnter:f.empty,onMouseLeave:f.empty,onDragStart:f.empty,onDragMove:f.empty,onDragCancel:f.empty,onDragEnd:f.empty,onTouchStart:f.empty,onTouchMove:f.empty,onTouchEnd:f.empty,onMouseWheel:f.empty};r.Navigation={$extend:!1,enable:!1,type:"auto",panning:!1,zooming:!1};r.Controller={$extend:!0,onBeforeCompute:f.empty,
    onAfterCompute:f.empty,onCreateLabel:f.empty,onPlaceLabel:f.empty,onComplete:f.empty,onBeforePlotLine:f.empty,onAfterPlotLine:f.empty,onBeforePlotNode:f.empty,onAfterPlotNode:f.empty,request:!1};var n={initialize:function(a,b){this.viz=b;this.canvas=b.canvas;this.config=b.config[a];this.nodeTypes=b.fx.nodeTypes;var c=this.config.type;this.labelContainer=(this.dom="auto"==c?"Native"!=b.config.Label.type:"Native"!=c)&&b.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:f.empty,
    setAsProperty:f.lambda(!1),isEnabled:function(){return this.config.enable},isLabel:function(a,b,c){var a=f.event.get(a,b),b=this.labelContainer,d=a.target||a.srcElement,a=a.relatedTarget;return c?a&&a==this.viz.canvas.getCtx().canvas&&!!d&&this.isDescendantOf(d,b):this.isDescendantOf(d,b)},isDescendantOf:function(a,b){for(;a&&a.parentNode;){if(a.parentNode==b)return a;a=a.parentNode}return!1}},y={onMouseUp:f.empty,onMouseDown:f.empty,onMouseMove:f.empty,onMouseOver:f.empty,onMouseOut:f.empty,onMouseWheel:f.empty,
    onTouchStart:f.empty,onTouchMove:f.empty,onTouchEnd:f.empty,onTouchCancel:f.empty},L=new k({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=!1;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),b=this;a.oncontextmenu=f.lambda(!1);f.addEvents(a,{mouseup:function(a,c){var g=f.event.get(a,c);b.handleEvent("MouseUp",a,c,b.makeEventObject(a,c),f.event.isRightClick(g))},mousedown:function(a,c){var g=f.event.get(a,c);b.handleEvent("MouseDown",
    a,c,b.makeEventObject(a,c),f.event.isRightClick(g))},mousemove:function(a,c){b.handleEvent("MouseMove",a,c,b.makeEventObject(a,c))},mouseover:function(a,c){b.handleEvent("MouseOver",a,c,b.makeEventObject(a,c))},mouseout:function(a,c){b.handleEvent("MouseOut",a,c,b.makeEventObject(a,c))},touchstart:function(a,c){b.handleEvent("TouchStart",a,c,b.makeEventObject(a,c))},touchmove:function(a,c){b.handleEvent("TouchMove",a,c,b.makeEventObject(a,c))},touchend:function(a,c){b.handleEvent("TouchEnd",a,c,b.makeEventObject(a,
    c))}});var c=function(a,c){var g=f.event.get(a,c),g=f.event.getWheel(g);b.handleEvent("MouseWheel",a,c,g)};!document.getBoxObjectFor&&null==window.mozInnerScreenX?f.addEvent(a,"mousewheel",c):a.addEventListener("DOMMouseScroll",c,!1)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),b=a.shift(),c=0,d=this.registeredObjects,e=d.length;c<e;c++)d[c]["on"+b].apply(d[c],a)},makeEventObject:function(a,b){var c=this,d=this.viz.graph,
    e=this.viz.fx,g=e.nodeTypes,h=e.edgeTypes;return{pos:!1,node:!1,edge:!1,contains:!1,getNodeCalled:!1,getEdgeCalled:!1,getPos:function(){var d=c.viz.canvas,e=d.getSize(),g=d.getPos(),h=d.translateOffsetX,q=d.translateOffsetY,v=d.scaleOffsetX,d=d.scaleOffsetY,k=f.event.getPos(a,b);return this.pos={x:1*(k.x-g.x-e.width/2-h)/v,y:1*(k.y-g.y-e.height/2-q)/d}},getNode:function(){if(this.getNodeCalled)return this.node;this.getNodeCalled=!0;for(var a in d.nodes){var b=d.nodes[a],f=b&&g[b.getData("type")];
    if(f=f&&f.contains&&f.contains.call(e,b,this.getPos()))return this.contains=f,c.node=this.node=b}return c.node=this.node=!1},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=!0;var a={},b;for(b in d.edges){var g=d.edges[b];a[b]=!0;for(var f in g)if(!(f in a)){var q=g[f],v=q&&h[q.getData("type")];if(v=v&&v.contains&&v.contains.call(e,q,this.getPos()))return this.contains=v,c.edge=this.edge=q}}return c.edge=this.edge=!1},getContains:function(){if(this.getNodeCalled)return this.contains;
    this.getNode();return this.contains}}}}),w={initializeExtras:function(){var a=new L(this),b=this;f.each(["NodeStyles","Tips","Navigation","Events"],function(c){var d=new w.Classes[c](c,b);d.isEnabled()&&a.register(d);d.setAsProperty()&&(b[c.toLowerCase()]=d)})},Classes:{}};w.Classes.Events=new k({Implements:[n,y],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=!1},setAsProperty:f.lambda(!0),
    onMouseUp:function(a,b,c,d){a=f.event.get(a,b);if(!this.moved)if(d)this.config.onRightClick(this.hovered,c,a);else this.config.onClick(this.pressed,c,a);if(this.pressed){if(this.moved)this.config.onDragEnd(this.pressed,c,a);else this.config.onDragCancel(this.pressed,c,a);this.pressed=this.moved=!1}},onMouseOut:function(a,b,c){var d=f.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,b,!0)))this.config.onMouseLeave(this.viz.graph.getNode(e.id),c,d),this.hovered=!1;else{a=d.relatedTarget;for(b=this.canvas.getElement();a&&
        a.parentNode;){if(b==a.parentNode)return;a=a.parentNode}this.hovered&&(this.config.onMouseLeave(this.hovered,c,d),this.hovered=!1)}},onMouseOver:function(a,b,c){var d=f.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,b,!0)))this.hovered=this.viz.graph.getNode(e.id),this.config.onMouseEnter(this.hovered,c,d)},onMouseMove:function(a,b,c){a=f.event.get(a,b);if(this.pressed)this.moved=!0,this.config.onDragMove(this.pressed,c,a);else if(this.dom)this.config.onMouseMove(this.hovered,c,a);else{if(this.hovered){var b=
        this.hovered,d=b.nodeFrom?this.etypes[b.getData("type")]:this.ntypes[b.getData("type")];if(d&&d.contains&&d.contains.call(this.fx,b,c.getPos())){this.config.onMouseMove(b,c,a);return}this.config.onMouseLeave(b,c,a);this.hovered=!1}if(this.hovered=c.getNode()||this.config.enableForEdges&&c.getEdge())this.config.onMouseEnter(this.hovered,c,a);else this.config.onMouseMove(!1,c,a)}},onMouseWheel:function(a,b,c){this.config.onMouseWheel(c,f.event.get(a,b))},onMouseDown:function(a,b,c){var d=f.event.get(a,
        b);if(this.dom){if(a=this.isLabel(a,b))this.pressed=this.viz.graph.getNode(a.id)}else this.pressed=c.getNode()||this.config.enableForEdges&&c.getEdge();this.pressed&&this.config.onDragStart(this.pressed,c,d)},onTouchStart:function(a,b,c){var d=f.event.get(a,b),e;(this.touched=this.dom&&(e=this.isLabel(a,b))?this.viz.graph.getNode(e.id):c.getNode()||this.config.enableForEdges&&c.getEdge())&&this.config.onTouchStart(this.touched,c,d)},onTouchMove:function(a,b,c){a=f.event.get(a,b);this.touched&&(this.touchMoved=
        !0,this.config.onTouchMove(this.touched,c,a))},onTouchEnd:function(a,b,c){a=f.event.get(a,b);if(this.touched){if(this.touchMoved)this.config.onTouchEnd(this.touched,c,a);else this.config.onTouchCancel(this.touched,c,a);this.touched=this.touchMoved=!1}}});w.Classes.Tips=new k({Implements:[n,y],initializePost:function(){if(document.body){var a=f("_tooltip")||document.createElement("div");a.id="_tooltip";a.className="tip";f.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);
    this.tip=a;this.node=!1}},setAsProperty:f.lambda(!0),onMouseOut:function(a,b){f.event.get(a,b);if(this.dom&&this.isLabel(a,b,!0))this.hide(!0);else{for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.hide(!1)}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b,!1)))this.node=this.viz.graph.getNode(c.id),this.config.onShow(this.tip,this.node,c)},onMouseMove:function(a,b,c){this.dom&&this.isLabel(a,b)&&this.setTooltipPosition(f.event.getPos(a,
    b));if(!this.dom){var d=c.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id)this.node=d,this.config.onShow(this.tip,d,c.getContains());this.setTooltipPosition(f.event.getPos(a,b))}else this.hide(!0)}},setTooltipPosition:function(a){var b=this.tip,c=b.style,d=this.config;c.display="";var e=document.body.clientWidth,g=b.offsetWidth,b=b.offsetHeight,f=d.offsetX,d=d.offsetY;c.top=(a.y+d+b>document.body.clientHeight?a.y-b-d:a.y+d)+"px";c.left=(a.x+g+f>e?a.x-g-f:a.x+f)+"px"},hide:function(a){this.tip.style.display=
    "none";a&&this.config.onHide()}});w.Classes.NodeStyles=new k({Implements:[n,y],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=!1;this.fx.nodeFxAnimation=new I;this.move=this.down=!1},onMouseOut:function(a,b){this.down=this.move=!1;if(this.hoveredNode){this.dom&&this.isLabel(a,b,!0)&&this.toggleStylesOnHover(this.hoveredNode,!1);for(var c=
    a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.toggleStylesOnHover(this.hoveredNode,!1);this.hoveredNode=!1}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b,!0)))c=this.viz.graph.getNode(c.id),c.selected||(this.hoveredNode=c,this.toggleStylesOnHover(this.hoveredNode,!0))},onMouseDown:function(a,b,c,d){if(!d){var e;this.dom&&(e=this.isLabel(a,b))?this.down=this.viz.graph.getNode(e.id):this.dom||(this.down=c.getNode());this.move=
    !1}},onMouseUp:function(a,b,c,d){if(!d){if(!this.move)this.onClick(c.getNode());this.down=this.move=!1}},getRestoredStyles:function(a,b){var c={},d=this["nodeStylesOn"+b],e;for(e in d)c[e]=a.styles["$"+e];return c},toggleStylesOnHover:function(a,b){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",a,b)},toggleStylesOnClick:function(a,b){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,b)},toggleStylesOn:function(a,b,c){var d=this.viz;if(c){b.styles||(b.styles=f.merge(b.data,{}));for(var e in this["nodeStylesOn"+
    a])c="$"+e,c in b.styles||(b.styles[c]=b.getData(e));d.fx.nodeFx(f.extend({elements:{id:b.id,properties:this["nodeStylesOn"+a]},transition:x.Quart.easeOut,duration:300,fps:40},this.config))}else a=this.getRestoredStyles(b,a),d.fx.nodeFx(f.extend({elements:{id:b.id,properties:a},transition:x.Quart.easeOut,duration:300,fps:40},this.config))},onClick:function(a){if(a){var b=this.nodeStylesOnClick;b&&(a.selected?(this.toggleStylesOnClick(a,!1),delete a.selected):(this.viz.graph.eachNode(function(a){if(a.selected){for(var d in b)a.setData(d,
    a.styles["$"+d],"end");delete a.selected}}),this.toggleStylesOnClick(a,!0),a.selected=!0,delete a.hovered,this.hoveredNode=!1))}},onMouseMove:function(a,b,c){this.down&&(this.move=!0);if(!this.dom||!this.isLabel(a,b)){var d=this.nodeStylesOnHover;if(d&&!this.dom){if(this.hoveredNode&&(a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,c.getPos()))return;c=c.getNode();if((this.hoveredNode||c)&&!c.hovered)c&&!c.selected?(this.fx.nodeFxAnimation.stopTimer(),
    this.viz.graph.eachNode(function(a){if(a.hovered&&!a.selected){for(var b in d)a.setData(b,a.styles["$"+b],"end");delete a.hovered}}),c.hovered=!0,this.hoveredNode=c,this.toggleStylesOnHover(c,!0)):this.hoveredNode&&!this.hoveredNode.selected&&(this.fx.nodeFxAnimation.stopTimer(),this.toggleStylesOnHover(this.hoveredNode,!1),delete this.hoveredNode.hovered,this.hoveredNode=!1)}}}});w.Classes.Navigation=new k({Implements:[n,y],initializePost:function(){this.pressed=this.pos=!1},onMouseWheel:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           b,c){this.config.zooming&&(f.event.stop(f.event.get(a,b)),a=1+c*(this.config.zooming/1E3),this.canvas.scale(a,a))},onMouseDown:function(a,b,c){if(this.config.panning&&!("avoid nodes"==this.config.panning&&(this.dom?this.isLabel(a,b):c.getNode()))){this.pressed=!0;this.pos=c.getPos();var a=this.canvas,b=a.translateOffsetX,c=a.translateOffsetY,d=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=b;this.pos.y*=d;this.pos.y+=c}},onMouseMove:function(a,b,c){if(this.config.panning&&this.pressed&&!("avoid nodes"==
    this.config.panning&&(this.dom?this.isLabel(a,b):c.getNode()))){var a=this.pos,c=c.getPos(),d=this.canvas,e=d.translateOffsetX,g=d.translateOffsetY,b=d.scaleOffsetX,d=d.scaleOffsetY;c.x*=b;c.y*=d;c.x+=e;c.y+=g;e=c.x-a.x;a=c.y-a.y;this.pos=c;this.canvas.translate(1*e/b,1*a/d)}},onMouseUp:function(){this.config.panning&&(this.pressed=!1)}});var s,C=function(a,b){var c=document.createElement(a),d;for(d in b)"object"==typeof b[d]?f.extend(c[d],b[d]):c[d]=b[d];"canvas"==a&&(!J&&G_vmlCanvasManager)&&(c=
    G_vmlCanvasManager.initElement(document.body.appendChild(c)));return c},n=typeof HTMLCanvasElement,J="object"==n||"function"==n;$jit.Canvas=s=new k({canvases:[],pos:!1,element:!1,labelContainer:!1,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a,b){this.viz=a;this.opt=this.config=b;var c="string"==f.type(b.injectInto)?b.injectInto:b.injectInto.id,d=b.type,e=c+"-label",g=f(c),h=b.width||g.offsetWidth,i=b.height||g.offsetHeight;this.id=c;var j={injectInto:c,
    width:h,height:i};this.element=C("div",{id:c+"-canvaswidget",style:{position:"relative",width:h+"px",height:i+"px"}});this.labelContainer=this.createLabelContainer(b.Label.type,e,j);this.canvases.push(new s.Base[d]({config:f.extend({idSuffix:"-canvas"},j),plot:function(){a.fx.plot()},resize:function(){a.refresh()}}));if(c=b.background)j=new s.Background[c.type](a,f.extend(c,j)),this.canvases.push(new s.Base[d](j));for(d=this.canvases.length;d--;)this.element.appendChild(this.canvases[d].canvas),0<
    d&&this.canvases[d].plot();this.element.appendChild(this.labelContainer);g.appendChild(this.element);var m=null,t=this;f.addEvent(window,"scroll",function(){clearTimeout(m);m=setTimeout(function(){t.getPos(!0)},500)})},getCtx:function(a){return this.canvases[a||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},getSize:function(a){return this.canvases[a||0].getSize()},resize:function(a,b){this.getPos(!0);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=
    this.scaleOffsetY=1;for(var c=0,d=this.canvases.length;c<d;c++)this.canvases[c].resize(a,b);c=this.element.style;c.width=a+"px";c.height=b+"px";this.labelContainer&&(this.labelContainer.style.width=a+"px")},translate:function(a,b,c){this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*this.scaleOffsetY;for(var d=0,e=this.canvases.length;d<e;d++)this.canvases[d].translate(a,b,c)},scale:function(a,b){var c=this.scaleOffsetX*a,d=this.scaleOffsetY*b,e=this.translateOffsetX*(a-1)/c,g=this.translateOffsetY*
    (b-1)/d;this.scaleOffsetX=c;this.scaleOffsetY=d;c=0;for(d=this.canvases.length;c<d;c++)this.canvases[c].scale(a,b,!0);this.translate(e,g,!1)},getPos:function(a){return a||!this.pos?this.pos=f.getPos(this.getElement()):this.pos},clear:function(a){this.canvases[a||0].clear()},path:function(a,b){var c=this.canvases[0].getCtx();c.beginPath();b(c);c[a]();c.closePath()},createLabelContainer:function(a,b,c){if("HTML"==a||"Native"==a)return C("div",{id:b,style:{overflow:"visible",position:"absolute",top:0,
    left:0,width:c.width+"px",height:0}});if("SVG"==a){a=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");a.setAttribute("width",c.width);a.setAttribute("height",c.height);var d=a.style;d.position="absolute";d.left=d.top="0px";d=document.createElementNS("http://www.w3.org/2000/svg","svg:g");d.setAttribute("width",c.width);d.setAttribute("height",c.height);d.setAttribute("x",0);d.setAttribute("y",0);d.setAttribute("id",b);a.appendChild(d);return a}}});s.Base={};s.Base["2D"]=new k({translateOffsetX:0,
    translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a){this.viz=a;this.opt=a.config;this.size=!1;this.createCanvas();this.translateToCenter()},createCanvas:function(){var a=this.opt,b=a.width,c=a.height;this.canvas=C("canvas",{id:a.injectInto+a.idSuffix,width:b,height:c,style:{position:"absolute",top:0,left:0,width:b+"px",height:c+"px"}})},getCtx:function(){return!this.ctx?this.ctx=this.canvas.getContext("2d"):this.ctx},getSize:function(){if(this.size)return this.size;var a=this.canvas;
        return this.size={width:a.width,height:a.height}},translateToCenter:function(a){var b=this.getSize(),c=a?b.width-a.width-2*this.translateOffsetX:b.width;height=a?b.height-a.height-2*this.translateOffsetY:b.height;b=this.getCtx();a&&b.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);b.translate(c/2,height/2)},resize:function(a,b){var c=this.getSize(),d=this.canvas,e=d.style;this.size=!1;d.width=a;d.height=b;e.width=a+"px";e.height=b+"px";J?this.translateToCenter():this.translateToCenter(c);this.translateOffsetX=
        this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(a,b,this)},translate:function(a,b,c){var d=this.scaleOffsetY;this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*d;this.getCtx().translate(a,b);!c&&this.plot()},scale:function(a,b,c){this.scaleOffsetX*=a;this.scaleOffsetY*=b;this.getCtx().scale(a,b);!c&&this.plot()},clear:function(){var a=this.getSize(),b=this.translateOffsetX,c=this.translateOffsetY,d=this.scaleOffsetX,e=this.scaleOffsetY;this.getCtx().clearRect(1*
        (-a.width/2-b)/d,1*(-a.height/2-c)/e,1*a.width/d,1*a.height/e)},plot:function(){this.clear();this.viz.plot(this)}});s.Background={};s.Background.Circles=new k({initialize:function(a,b){this.viz=a;this.config=f.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},offset:0},b)},resize:function(a,b,c){this.plot(c)},plot:function(a){var a=a.getCtx(),b=this.config,c=b.CanvasStyles,d;for(d in c)a[d]=c[d];d=b.numberOfCircles;b=b.levelDistance;for(c=1;c<=d;c++)a.beginPath(),a.arc(0,
    0,b*c,0,2*Math.PI,!1),a.stroke(),a.closePath()}});var u=function(a,b){this.theta=a||0;this.rho=b||0};$jit.Polar=u;u.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,b){this.rho=Math.sqrt(a*a+b*b);this.theta=Math.atan2(b,a);0>this.theta&&(this.theta+=2*Math.PI)},setp:function(a,b){this.theta=a;this.rho=b},clone:function(){return new u(this.theta,this.rho)},toComplex:function(a){var b=Math.cos(this.theta)*
    this.rho,c=Math.sin(this.theta)*this.rho;return a?{x:b,y:c}:new o(b,c)},add:function(a){return new u(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new u(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=a.theta;this.rho+=a.rho;return this},$madd:function(a){this.theta=(this.theta+a.theta)%(2*Math.PI);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},isZero:function(){var a=Math.abs;return 1E-4>
    a(this.theta)&&1E-4>a(this.rho)},interpolate:function(a,b){var c=Math.PI,d=2*c,e=function(a){return 0>a?a%d+d:a%d},g=this.theta,f=a.theta,i=Math.abs(g-f);return{theta:i==c?g>f?e(f+(g-d-f)*b):e(f-d+(g-f)*b):i>=c?g>f?e(f+(g-d-f)*b):e(f-d+(g-(f-d))*b):e(f+(g-f)*b),rho:(this.rho-a.rho)*b+a.rho}}};u.KER=new u(0,0);var o=function(a,b){this.x=a||0;this.y=b||0};$jit.Complex=o;o.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(!0);this.x=a.x;this.y=
    a.y},setc:function(a,b){this.x=a;this.y=b},setp:function(a,b){this.x=Math.cos(a)*b;this.y=Math.sin(a)*b},clone:function(){return new o(this.x,this.y)},toPolar:function(a){var b=this.norm(),c=Math.atan2(this.y,this.x);0>c&&(c+=2*Math.PI);return a?{theta:c,rho:b}:new u(c,b)},norm:function(){return Math.sqrt(this.squaredNorm())},squaredNorm:function(){return this.x*this.x+this.y*this.y},add:function(a){return new o(this.x+a.x,this.y+a.y)},prod:function(a){return new o(this.x*a.x-this.y*a.y,this.y*a.x+
    this.x*a.y)},conjugate:function(){return new o(this.x,-this.y)},scale:function(a){return new o(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var b=this.x,c=this.y;this.x=b*a.x-c*a.y;this.y=c*a.x+b*a.y;return this},$conjugate:function(){this.y=-this.y;return this},$scale:function(a){this.x*=a;this.y*=a;return this},$div:function(a){var b=this.x,c=this.y,d=a.squaredNorm();this.x=b*a.x+c*a.y;this.y=c*a.x-
    b*a.y;return this.$scale(1/d)},isZero:function(){var a=Math.abs;return 1E-4>a(this.x)&&1E-4>a(this.y)}};var A=function(a,b){return new o(a,b)};o.KER=A(0,0);$jit.Graph=new k({initialize:function(a,b,c,d){var e={klass:o,Node:{}};this.Node=b;this.Edge=c;this.Label=d;this.opt=f.merge(e,a||{});this.nodes={};this.edges={};var g=this;this.nodeList={};for(var h in B)g.nodeList[h]=function(a){return function(){var b=Array.prototype.slice.call(arguments);g.eachNode(function(c){c[a].apply(c,b)})}}(h)},getNode:function(a){return this.hasNode(a)?
    this.nodes[a]:!1},get:function(a){return this.getNode(a)},getByName:function(a){for(var b in this.nodes){var c=this.nodes[b];if(c.name==a)return c}return!1},getAdjacence:function(a,b){return a in this.edges?this.edges[a][b]:!1},addNode:function(a){if(!this.nodes[a.id]){var b=this.edges[a.id]={};this.nodes[a.id]=new l.Node(f.extend({id:a.id,name:a.name,data:f.merge(a.data||{},{}),adjacencies:b},this.opt.Node),this.opt.klass,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},addAdjacence:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              b,c){this.hasNode(a.id)||this.addNode(a);this.hasNode(b.id)||this.addNode(b);a=this.nodes[a.id];b=this.nodes[b.id];if(!a.adjacentTo(b)){var d=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[b.id]=this.edges[b.id]||{};d[b.id]=e[a.id]=new l.Adjacence(a,b,c,this.Edge,this.Label);return d[b.id]}return this.edges[a.id][b.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];var b=this.edges[a],c;for(c in b)delete this.edges[c][a];delete this.edges[a]}},removeAdjacence:function(a,b){delete this.edges[a][b];
    delete this.edges[b][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var l=$jit.Graph,B,D=function(a,b,c,d,e){var g,c=c||"current";"current"==c?g=this.data:"start"==c?g=this.startData:"end"==c&&(g=this.endData);a="$"+(a?a+"-":"")+b;return d?g[a]:!this.Config.overridable?e[b]||0:a in g?g[a]:a in this.data?this.data[a]:e[b]||0},E=function(a,b,c,d){var d=d||"current",e;"current"==d?e=this.data:"start"==d?e=this.startData:"end"==d&&(e=this.endData);e["$"+
    (a?a+"-":"")+b]=c},F=function(a,b){var a="$"+(a?a+"-":""),c=this;f.each(b,function(b){b=a+b;delete c.data[b];delete c.endData[b];delete c.startData[b]})};B={getData:function(a,b,c){return D.call(this,"",a,b,c,this.Config)},setData:function(a,b,c){E.call(this,"",a,b,c)},setDataset:function(a,b){var a=f.splat(a),c;for(c in b)for(var d=0,e=f.splat(b[c]),g=a.length;d<g;d++)this.setData(c,e[d],a[d])},removeData:function(){F.call(this,"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        b,c){return D.call(this,"canvas",a,b,c,this.Config.CanvasStyles)},setCanvasStyle:function(a,b,c){E.call(this,"canvas",a,b,c)},setCanvasStyles:function(a,b){var a=f.splat(a),c;for(c in b)for(var d=0,e=f.splat(b[c]),g=a.length;d<g;d++)this.setCanvasStyle(c,e[d],a[d])},removeCanvasStyle:function(){F.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(a,b,c){return D.call(this,"label",a,b,c,this.Label)},setLabelData:function(a,b,c){E.call(this,"label",a,b,c)},setLabelDataset:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          b){var a=f.splat(a),c;for(c in b)for(var d=0,e=f.splat(b[c]),g=a.length;d<g;d++)this.setLabelData(c,e[d],a[d])},removeLabelData:function(){F.call(this,"label",Array.prototype.slice.call(arguments))}};l.Node=new k({initialize:function(a,b,c,d,e){b={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:!1,drawn:!1,exist:!1,angleSpan:{begin:0,end:0},pos:new b,startPos:new b,endPos:new b};f.extend(this,f.extend(b,a));this.Config=this.Node=c;this.Edge=d;this.Label=e},adjacentTo:function(a){return a.id in
    this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if("current"==a)return this.pos;if("end"==a)return this.endPos;if("start"==a)return this.startPos},setPos:function(a,b){var b=b||"current",c;"current"==b?c=this.pos:"end"==b?c=this.endPos:"start"==b&&(c=this.startPos);c.set(a)}});l.Node.implement(B);l.Adjacence=new k({initialize:function(a,b,c,d,e){this.nodeFrom=a;this.nodeTo=b;this.data=c||{};this.startData={};this.endData={};this.Config=this.Edge=
    d;this.Label=e}});l.Adjacence.implement(B);l.Util={filter:function(a){if(!a||"string"!=f.type(a))return function(){return!0};var b=a.split(" ");return function(a){for(var d=0;d<b.length;d++)if(a[b[d]])return!1;return!0}},getNode:function(a,b){return a.nodes[b]},eachNode:function(a,b,c){var c=this.filter(c),d;for(d in a.nodes)c(a.nodes[d])&&b(a.nodes[d])},each:function(a,b,c){this.eachNode(a,b,c)},eachAdjacency:function(a,b,c){var d=a.adjacencies,c=this.filter(c),e;for(e in d){var g=d[e];if(c(g)){if(g.nodeFrom!=
    a){var f=g.nodeFrom;g.nodeFrom=g.nodeTo;g.nodeTo=f}b(g,e)}}},computeLevels:function(a,b,c,d){var c=c||0,e=this.filter(d);this.eachNode(a,function(a){a._flag=!1;a._depth=-1},d);a=a.getNode(b);a._depth=c;for(var g=[a];0!=g.length;){var f=g.pop();f._flag=!0;this.eachAdjacency(f,function(a){a=a.nodeTo;!1==a._flag&&e(a)&&(0>a._depth&&(a._depth=f._depth+1+c),g.unshift(a))},d)}},eachBFS:function(a,b,c,d){var e=this.filter(d);this.clean(a);for(var g=[a.getNode(b)];0!=g.length;)a=g.pop(),a._flag=!0,c(a,a._depth),
    this.eachAdjacency(a,function(a){a=a.nodeTo;!1==a._flag&&e(a)&&(a._flag=!0,g.unshift(a))},d)},eachLevel:function(a,b,c,d,e){var g=a._depth,f=this.filter(e),i=this,c=!1===c?Number.MAX_VALUE-g:c;(function m(a,b,c){var e=a._depth;e>=b&&(e<=c&&f(a))&&d(a,e);e<c&&i.eachAdjacency(a,function(a){a=a.nodeTo;a._depth>e&&m(a,b,c)})})(a,b+g,c+g)},eachSubgraph:function(a,b,c){this.eachLevel(a,0,!1,b,c)},eachSubnode:function(a,b,c){this.eachLevel(a,1,1,b,c)},anySubnode:function(a,b,c){var d=!1,b=b||f.lambda(!0),
    e="string"==f.type(b)?function(a){return a[b]}:b;this.eachSubnode(a,function(a){e(a)&&(d=!0)},c);return d},getSubnodes:function(a,b,c){var d=[],b=b||0,e;"array"==f.type(b)?(e=b[0],b=b[1]):(e=b,b=Number.MAX_VALUE-a._depth);this.eachLevel(a,e,b,function(a){d.push(a)},c);return d},getParents:function(a){var b=[];this.eachAdjacency(a,function(c){c=c.nodeTo;c._depth<a._depth&&b.push(c)});return b},isDescendantOf:function(a,b){if(a.id==b)return!0;for(var c=this.getParents(a),d=!1,e=0;!d&&e<c.length;e++)d=
    d||this.isDescendantOf(c[e],b);return d},clean:function(a){this.eachNode(a,function(a){a._flag=!1})},getClosestNodeToOrigin:function(a,b,c){return this.getClosestNodeToPos(a,u.KER,b,c)},getClosestNodeToPos:function(a,b,c,d){var e=null,c=c||"current",b=b&&b.getc(!0)||o.KER,g=function(a,b){var c=a.x-b.x,d=a.y-b.y;return c*c+d*d};this.eachNode(a,function(a){e=null==e||g(a.getPos(c).getc(!0),b)<g(e.getPos(c).getc(!0),b)?a:e},d);return e}};f.each("get getNode each eachNode computeLevels eachBFS clean getClosestNodeToPos getClosestNodeToOrigin".split(" "),
    function(a){l.prototype[a]=function(){return l.Util[a].apply(l.Util,[this].concat(Array.prototype.slice.call(arguments)))}});f.each("eachAdjacency eachLevel eachSubgraph eachSubnode anySubnode getSubnodes getParents isDescendantOf".split(" "),function(a){l.Node.prototype[a]=function(){return l.Util[a].apply(l.Util,[this].concat(Array.prototype.slice.call(arguments)))}});l.Op={options:{type:"nothing",duration:2E3,hideLabels:!0,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,b){var c=
    this.viz,d=f.merge(this.options,c.controller,b),e=f.splat(a),g,h,i;switch(d.type){case "nothing":for(g=0;g<e.length;g++)c.graph.removeNode(e[g]);break;case "replot":this.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.refresh(!0);break;case "fade:seq":case "fade":h=this;for(g=0;g<e.length;g++)i=c.graph.getNode(e[g]),i.setData("alpha",0,"end");c.fx.animate(f.merge(d,{modes:["node-property:alpha"],onComplete:function(){h.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.reposition();c.fx.animate(f.merge(d,
    {modes:["linear"]}))}}));break;case "fade:con":h=this;for(g=0;g<e.length;g++)i=c.graph.getNode(e[g]),i.setData("alpha",0,"end"),i.ignore=!0;c.reposition();c.fx.animate(f.merge(d,{modes:["node-property:alpha","linear"],onComplete:function(){h.removeNode(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));break;case "iter":h=this;c.fx.sequence({condition:function(){return 0!=e.length},step:function(){h.removeNode(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete&&
d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,b){var c=this.viz,d=f.merge(this.options,c.controller,b),e="string"==f.type(a[0])?[a]:a,g,h,i;switch(d.type){case "nothing":for(g=0;g<e.length;g++)c.graph.removeAdjacence(e[g][0],e[g][1]);break;case "replot":this.removeEdge(e,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":h=this;for(g=0;g<e.length;g++)(i=c.graph.getAdjacence(e[g][0],e[g][1]))&&i.setData("alpha",0,"end");
    c.fx.animate(f.merge(d,{modes:["edge-property:alpha"],onComplete:function(){h.removeEdge(e,{type:"nothing"});c.reposition();c.fx.animate(f.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(g=0;g<e.length;g++)if(i=c.graph.getAdjacence(e[g][0],e[g][1]))i.setData("alpha",0,"end"),i.ignore=!0;c.reposition();c.fx.animate(f.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){h.removeEdge(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));break;case "iter":h=this;c.fx.sequence({condition:function(){return 0!=
    e.length},step:function(){h.removeEdge(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},sum:function(a,b){var c=this.viz,d=f.merge(this.options,c.controller,b),e=c.root,g;c.root=b.id||c.root;switch(d.type){case "nothing":g=c.construct(a);g.eachNode(function(a){a.eachAdjacency(function(a){c.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data)})});break;case "replot":c.refresh(!0);this.sum(a,
    {type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;g=c.construct(a);var h=!this.preprocessSum(g)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];c.reposition();"fade:con"!=d.type?c.fx.animate(f.merge(d,{modes:["linear"],onComplete:function(){c.fx.animate(f.merge(d,{modes:h,onComplete:function(){d.onComplete()}}))}})):(c.graph.eachNode(function(a){a.id!=e&&a.pos.isZero()&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))}),c.fx.animate(f.merge(d,
    {modes:["linear"].concat(h)})));break;default:this.doError()}},morph:function(a,b,c){var c=c||{},d=this.viz,e=f.merge(this.options,d.controller,b),g=d.root,h;d.root=b.id||d.root;switch(e.type){case "nothing":h=d.construct(a);h.eachNode(function(a){var b=d.graph.hasNode(a.id);a.eachAdjacency(function(a){var b=!!d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id);d.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data);if(b){var b=d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id),c;for(c in a.data||{})b.data[c]=
    a.data[c]}});if(b){var b=d.graph.getNode(a.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});d.graph.eachNode(function(a){a.eachAdjacency(function(a){h.getAdjacence(a.nodeFrom.id,a.nodeTo.id)||d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)});h.hasNode(a.id)||d.graph.removeNode(a.id)});break;case "replot":d.labels.clearLabels(!0);this.morph(a,{type:"nothing"});d.refresh(!0);d.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;h=d.construct(a);var i="node-property"in c&&f.map(f.splat(c["node-property"]),
    function(a){return"$"+a});d.graph.eachNode(function(a){var b=h.getNode(a.id);if(b){var b=b.data,c;for(c in b)i&&-1<f.indexOf(i,c)?a.endData[c]=b[c]:a.data[c]=b[c]}else a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"),a.ignore=!0});d.graph.eachNode(function(a){a.ignore||a.eachAdjacency(function(a){if(!a.nodeFrom.ignore&&!a.nodeTo.ignore){var b=h.getNode(a.nodeFrom.id),a=h.getNode(a.nodeTo.id);b.adjacentTo(a)||(a=d.graph.getAdjacence(b.id,a.id),j=!0,a.setData("alpha",1),
    a.setData("alpha",1,"start"),a.setData("alpha",0,"end"))}})});var j=this.preprocessSum(h),a=!j?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+="node-property"in c?":"+f.splat(c["node-property"]).join(":"):"";a[1]=(a[1]||"edge-property:alpha")+("edge-property"in c?":"+f.splat(c["edge-property"]).join(":"):"");"label-property"in c&&a.push("label-property:"+f.splat(c["label-property"]).join(":"));d.reposition?d.reposition():d.compute("end");d.graph.eachNode(function(a){a.id!=
    g&&a.pos.getp().equals(u.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))});d.fx.animate(f.merge(e,{modes:[c.position||"polar"].concat(a),onComplete:function(){d.graph.eachNode(function(a){a.ignore&&d.graph.removeNode(a.id)});d.graph.eachNode(function(a){a.eachAdjacency(function(a){a.ignore&&d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)})});e.onComplete()}}))}},contract:function(a,b){var c=this.viz;!a.collapsed&&a.anySubnode(f.lambda(!0))&&(b=f.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span",
    "linear"]}),a.collapsed=!0,function e(a){a.eachSubnode(function(a){a.ignore=!0;a.setData("alpha",0,"animate"==b.type?"end":"current");e(a)})}(a),"animate"==b.type?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),function g(b){b.eachSubnode(function(b){b.setPos(a.getPos("end"),"end");g(b)})}(a),c.fx.animate(b)):"replot"==b.type&&c.refresh())},expand:function(a,b){if("collapsed"in a){var c=this.viz,b=f.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]});
    delete a.collapsed;(function e(a){a.eachSubnode(function(a){delete a.ignore;a.setData("alpha",1,"animate"==b.type?"end":"current");e(a)})})(a);"animate"==b.type?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),c.fx.animate(b)):"replot"==b.type&&c.refresh()}},preprocessSum:function(a){var b=this.viz;a.eachNode(function(a){b.graph.hasNode(a.id)||(b.graph.addNode(a),a=b.graph.getNode(a.id),a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end"))});var c=!1;
    a.eachNode(function(a){a.eachAdjacency(function(a){var d=b.graph.getNode(a.nodeFrom.id),f=b.graph.getNode(a.nodeTo.id);d.adjacentTo(f)||(a=b.graph.addAdjacence(d,f,a.data),d.startAlpha==d.endAlpha&&f.startAlpha==f.endAlpha&&(c=!0,a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end")))})});return c}};var G={none:{render:f.empty,contains:f.lambda(!1)},circle:{render:function(a,b,c,d){d=d.getCtx();d.beginPath();d.arc(b.x,b.y,c,0,2*Math.PI,!0);d.closePath();d[a]()},contains:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b,c){var d=a.x-b.x,a=a.y-b.y;return d*d+a*a<=c*c}},ellipse:{render:function(a,b,c,d,e){var e=e.getCtx(),f=1,h=1,i=1,j=1,m=0;c>d?(m=c/2,h=d/c,j=c/d):(m=d/2,f=c/d,i=d/c);e.save();e.scale(f,h);e.beginPath();e.arc(b.x*i,b.y*j,m,0,2*Math.PI,!0);e.closePath();e[a]();e.restore()},contains:function(a,b,c,d){var e=0,f=1,h=1,i=0,j=0;c>d?(e=c/2,h=d/c):(e=d/2,f=c/d);i=(a.x-b.x)*(1/f);j=(a.y-b.y)*(1/h);return i*i+j*j<=e*e}},square:{render:function(a,b,c,d){d.getCtx()[a+"Rect"](b.x-c,b.y-c,2*c,2*c)},contains:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            b,c){return Math.abs(b.x-a.x)<=c&&Math.abs(b.y-a.y)<=c}},rectangle:{render:function(a,b,c,d,e){e.getCtx()[a+"Rect"](b.x-c/2,b.y-d/2,c,d)},contains:function(a,b,c,d){return Math.abs(b.x-a.x)<=c/2&&Math.abs(b.y-a.y)<=d/2}},triangle:{render:function(a,b,c,d){var d=d.getCtx(),e=b.x,f=b.y-c,h=e-c,b=b.y+c,c=e+c;d.beginPath();d.moveTo(e,f);d.lineTo(h,b);d.lineTo(c,b);d.closePath();d[a]()},contains:function(a,b,c){return G.circle.contains(a,b,c)}},star:{render:function(a,b,c,d){var d=d.getCtx(),e=Math.PI/
    5;d.save();d.translate(b.x,b.y);d.beginPath();d.moveTo(c,0);for(b=0;9>b;b++)d.rotate(e),0==b%2?d.lineTo(0.200811*(c/0.525731),0):d.lineTo(c,0);d.closePath();d[a]();d.restore()},contains:function(a,b,c){return G.circle.contains(a,b,c)}}},K={line:{render:function(a,b,c){c=c.getCtx();c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()},contains:function(a,b,c,d){var e=Math.min,f=Math.max,h=e(a.x,b.x),i=f(a.x,b.x),e=e(a.y,b.y),f=f(a.y,b.y);return c.x>=h&&c.x<=i&&c.y>=e&&c.y<=f?Math.abs(b.x-a.x)<=
    d?!0:Math.abs((b.y-a.y)/(b.x-a.x)*(c.x-a.x)+a.y-c.y)<=d:!1}},arrow:{render:function(a,b,c,d,e){e=e.getCtx();d&&(d=a,a=b,b=d);d=new o(b.x-a.x,b.y-a.y);d.$scale(c/d.norm());var c=new o(b.x-d.x,b.y-d.y),f=new o(-d.y/2,d.x/2),d=c.add(f),c=c.$add(f.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(b.x,b.y);e.stroke();e.beginPath();e.moveTo(d.x,d.y);e.lineTo(c.x,c.y);e.lineTo(b.x,b.y);e.closePath();e.fill()},contains:function(a,b,c,d){return K.line.contains(a,b,c,d)}},hyperline:{render:function(a,b,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     c,d){var e,f,h,i,j;function m(a,b){return a<b?a+Math.PI>b?!1:!0:b+Math.PI>a?!0:!1}d=d.getCtx();e=a.x*b.y-a.y*b.x;f=a.squaredNorm();j=b.squaredNorm();0==e?(f=e=0,h=-1,j=i=void 0):(i=(a.y*j-b.y*f+a.y-b.y)/e,j=(b.x*f-a.x*j+b.x-a.x)/e,e=-i/2,f=-j/2,h=(i*i+j*j)/4-1,0>h?(f=e=0,h=-1,j=i=void 0):(h=Math.sqrt(h),h=1E3<h?-1:h));1E3<i||1E3<j||0>h?(d.beginPath(),d.moveTo(a.x*c,a.y*c),d.lineTo(b.x*c,b.y*c)):(b=Math.atan2(b.y-f,b.x-e),a=Math.atan2(a.y-f,a.x-e),m=m(b,a),d.beginPath(),d.arc(e*c,f*c,h*c,b,a,m));d.stroke()},
    contains:f.lambda(!1)}};l.Plot={initialize:function(a,b){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new I;this.nodeTypes=new b.Plot.NodeTypes;this.edgeTypes=new b.Plot.EdgeTypes;this.labels=a.labels},nodeHelper:G,edgeHelper:K,Interpolator:{map:{border:"color",color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",
    fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,b,c){return a+(b-a)*c},moebius:function(a,b,c,d){b=d.scale(-c);if(1>b.norm()){var c=b.x,d=b.y,e=a.startPos.getc().moebiusTransformation(b);a.pos.setc(e.x,e.y);b.x=c;b.y=d}},linear:function(a,b,c){var b=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,
    d.y,c))},polar:function(a,b,c){b=a.startPos.getp(!0);c=a.endPos.getp().interpolate(b,c);a.pos.setp(c.theta,c.rho)},number:function(a,b,c,d,e){var f=a[d](b,"start"),d=a[d](b,"end");a[e](b,this.compute(f,d,c))},color:function(a,b,c,d,e){var g=f.hexToRgb(a[d](b,"start")),d=f.hexToRgb(a[d](b,"end")),h=this.compute,c=f.rgbToHex([parseInt(h(g[0],d[0],c)),parseInt(h(g[1],d[1],c)),parseInt(h(g[2],d[2],c))]);a[e](b,c)},"array-number":function(a,b,c,d,e){for(var f=a[d](b,"start"),d=a[d](b,"end"),h=[],i=0,j=
    f.length;i<j;i++){var m=f[i],t=d[i];if(m.length){for(var q=0,k=m.length,l=[];q<k;q++)l.push(this.compute(m[q],t[q],c));h.push(l)}else h.push(this.compute(m,t,c))}a[e](b,h)},node:function(a,b,c,d,e,f){d=this[d];if(b)for(var h=b.length,i=0;i<h;i++){var j=b[i];this[d[j]](a,j,c,e,f)}else for(j in d)this[d[j]](a,j,c,e,f)},edge:function(a,b,c,d,e,f){var a=a.adjacencies,h;for(h in a)this.node(a[h],b,c,d,e,f)},"node-property":function(a,b,c){this.node(a,b,c,"map","getData","setData")},"edge-property":function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b,c){this.edge(a,b,c,"map","getData","setData")},"label-property":function(a,b,c){this.node(a,b,c,"label","getLabelData","setLabelData")},"node-style":function(a,b,c){this.node(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")},"edge-style":function(a,b,c){this.edge(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")}},sequence:function(a){var b=this,a=f.merge({condition:f.lambda(!1),step:f.empty,onComplete:f.empty,duration:200},a||{}),c=setInterval(function(){a.condition()?a.step():(clearInterval(c),
    a.onComplete());b.viz.refresh(!0)},a.duration)},prepare:function(a){var b=this.viz.graph,c={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},d={};if("array"==f.type(a))for(var e=0,g=a.length;e<g;e++){var h=a[e].split(":");d[h.shift()]=h}else for(e in a)"position"==e?d[a.position]=[]:d[e]=f.splat(a[e]);b.eachNode(function(a){a.startPos.set(a.pos);
    f.each(["node-property","node-style"],function(b){if(b in d)for(var e=d[b],f=0,g=e.length;f<g;f++)a[c[b].setter](e[f],a[c[b].getter](e[f]),"start")});f.each(["edge-property","edge-style"],function(b){if(b in d){var e=d[b];a.eachAdjacency(function(a){for(var d=0,f=e.length;d<f;d++)a[c[b].setter](e[d],a[c[b].getter](e[d]),"start")})}})});return d},animate:function(a,b){var a=f.merge(this.viz.config,a||{}),c=this,d=this.viz.graph,e=this.Interpolator,g="nodefx"===a.type?this.nodeFxAnimation:this.animation,
    h=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(!0);g.setOptions(f.extend(a,{$animating:!1,compute:function(f){d.eachNode(function(a){for(var c in h)e[c](a,h[c],f,b)});c.plot(a,this.$animating,f);this.$animating=!0},complete:function(){a.hideLabels&&c.labels.hideLabels(!1);c.plot(a);a.onComplete()}})).start()},nodeFx:function(a){var b=this.viz,c=b.graph,d=this.nodeFxAnimation,e=f.merge(this.viz.config,{elements:{id:!1,properties:{}},reposition:!1}),a=f.merge(e,a||{},{onBeforeCompute:f.empty,
    onAfterCompute:f.empty});d.stopTimer();var g=a.elements.properties;a.elements.id?(d=f.splat(a.elements.id),f.each(d,function(a){if(a=c.getNode(a))for(var b in g)a.setData(b,g[b],"end")})):c.eachNode(function(a){for(var b in g)a.setData(b,g[b],"end")});var d=[],h;for(h in g)d.push(h);h=["node-property:"+d.join(":")];a.reposition&&(h.push("linear"),b.compute("end"));this.animate(f.merge(a,{modes:h,type:"nodefx"}))},plot:function(a,b){var c=this.viz,d=c.graph,e=c.canvas,c=c.root,f=this;e.getCtx();a=
    a||this.viz.controller;a.clearCanvas&&e.clear();if(c=d.getNode(c)){var h=!!c.visited;d.eachNode(function(c){var d=c.getData("alpha");c.eachAdjacency(function(d){var j=d.nodeTo;!!j.visited===h&&(c.drawn&&j.drawn)&&(!b&&a.onBeforePlotLine(d),f.plotLine(d,e,b),!b&&a.onAfterPlotLine(d))});c.drawn&&(!b&&a.onBeforePlotNode(c),f.plotNode(c,e,b),!b&&a.onAfterPlotNode(c));!f.labelsHidden&&a.withLabels&&(c.drawn&&0.95<=d?f.labels.plotLabel(e,c,a):f.labels.hideLabel(c,!1));c.visited=!h})}},plotTree:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          b,c){var d=this,e=this.viz.canvas;e.getCtx();var f=a.getData("alpha");a.eachSubnode(function(f){if(b.plotSubtree(a,f)&&f.exist&&f.drawn){var g=a.getAdjacency(f.id);!c&&b.onBeforePlotLine(g);d.plotLine(g,e,c);!c&&b.onAfterPlotLine(g);d.plotTree(f,b,c)}});a.drawn?(!c&&b.onBeforePlotNode(a),this.plotNode(a,e,c),!c&&b.onAfterPlotNode(a),!b.hideLabels&&b.withLabels&&0.95<=f?this.labels.plotLabel(e,a,b):this.labels.hideLabel(a,!1)):this.labels.hideLabel(a,!0)},plotNode:function(a,b,c){var d=a.getData("type"),
    e=this.node.CanvasStyles;if("none"!=d){var f=a.getData("lineWidth"),h=a.getData("color"),i=a.getData("alpha"),j=b.getCtx();j.save();j.lineWidth=f;j.fillStyle=j.strokeStyle=h;j.globalAlpha=i;for(var m in e)j[m]=a.getCanvasStyle(m);this.nodeTypes[d].render.call(this,a,b,c);j.restore()}},plotLine:function(a,b,c){var d=a.getData("type"),e=this.edge.CanvasStyles;if("none"!=d){var f=a.getData("lineWidth"),h=a.getData("color"),i=b.getCtx(),j=a.nodeFrom,m=a.nodeTo;i.save();i.lineWidth=f;i.fillStyle=i.strokeStyle=
    h;i.globalAlpha=Math.min(j.getData("alpha"),m.getData("alpha"),a.getData("alpha"));for(var k in e)i[k]=a.getCanvasStyle(k);this.edgeTypes[d].render.call(this,a,b,c);i.restore()}}};l.Plot3D=f.merge(l.Plot,{Interpolator:{linear:function(a,b,c){var b=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,d.y,c),this.compute(b.z,d.z,c))}},plotNode:function(a,b){"none"!=a.getData("type")&&this.plotElement(a,b,{getAlpha:function(){return a.getData("alpha")}})},plotLine:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      b){"none"!=a.getData("type")&&this.plotElement(a,b,{getAlpha:function(){return Math.min(a.nodeFrom.getData("alpha"),a.nodeTo.getData("alpha"),a.getData("alpha"))}})},plotElement:function(a,b,c){var d=b.getCtx(),e=new Matrix4,g=b.config.Scene.Lighting,h=b.canvases[0],b=h.program,h=h.camera;a.geometry||(a.geometry=new (O3D[a.getData("type")]));a.geometry.update(a);if(!a.webGLVertexBuffer){for(var i=[],j=[],k=[],t=0,q=a.geometry,l=0,z=q.vertices,q=q.faces,n=q.length;l<n;l++){var p=q[l],o=z[p.a],r=z[p.b],
    u=z[p.c],s=p.d?z[p.d]:!1,p=p.normal;i.push(o.x,o.y,o.z);i.push(r.x,r.y,r.z);i.push(u.x,u.y,u.z);s&&i.push(s.x,s.y,s.z);k.push(p.x,p.y,p.z);k.push(p.x,p.y,p.z);k.push(p.x,p.y,p.z);s&&k.push(p.x,p.y,p.z);j.push(t,t+1,t+2);s?(j.push(t,t+2,t+3),t+=4):t+=3}a.webGLVertexBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.bufferData(d.ARRAY_BUFFER,new Float32Array(i),d.STATIC_DRAW);a.webGLFaceBuffer=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.bufferData(d.ELEMENT_ARRAY_BUFFER,
    new Uint16Array(j),d.STATIC_DRAW);a.webGLFaceCount=j.length;a.webGLNormalBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);d.bufferData(d.ARRAY_BUFFER,new Float32Array(k),d.STATIC_DRAW)}e.multiply(h.matrix,a.geometry.matrix);d.uniformMatrix4fv(b.viewMatrix,!1,e.flatten());d.uniformMatrix4fv(b.projectionMatrix,!1,h.projectionMatrix.flatten());e=Matrix4.makeInvert(e);e.$transpose();d.uniformMatrix4fv(b.normalMatrix,!1,e.flatten());e=f.hexToRgb(a.getData("color"));e.push(c.getAlpha());
    d.uniform4f(b.color,e[0]/255,e[1]/255,e[2]/255,e[3]);d.uniform1i(b.enableLighting,g.enable);if(g.enable&&(g.ambient&&(c=g.ambient,d.uniform3f(b.ambientColor,c[0],c[1],c[2])),g.directional))g=g.directional,e=g.color,g=g.direction,g=(new Vector3(g.x,g.y,g.z)).normalize().$scale(-1),d.uniform3f(b.lightingDirection,g.x,g.y,g.z),d.uniform3f(b.directionalColor,e[0],e[1],e[2]);d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.vertexAttribPointer(b.position,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ARRAY_BUFFER,
        a.webGLNormalBuffer);d.vertexAttribPointer(b.normal,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.drawElements(d.TRIANGLES,a.webGLFaceCount,d.UNSIGNED_SHORT,0)}});l.Label={};l.Label.Native=new k({initialize:function(a){this.viz=a},plotLabel:function(a,b,c){var d=a.getCtx();b.pos.getc(!0);d.font=b.getLabelData("style")+" "+b.getLabelData("size")+"px "+b.getLabelData("family");d.textAlign=b.getLabelData("textAlign");d.fillStyle=d.strokeStyle=b.getLabelData("color");d.textBaseline=
    b.getLabelData("textBaseline");this.renderLabel(a,b,c)},renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(!0);c.fillText(b.name,d.x,d.y+b.getData("height")/2)},hideLabel:f.empty,hideLabels:f.empty});l.Label.DOM=new k({labelsHidden:!1,labelContainer:!1,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},getLabel:function(a){return a in this.labels&&null!=this.labels[a]?this.labels[a]:
    this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var b in this.labels)if(a||!this.viz.graph.hasNode(b))this.disposeLabel(b),delete this.labels[b]},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,b){var a=f.splat(a),c=b?"":"none",d=this;f.each(a,function(a){if(a=d.getLabel(a.id))a.style.display=c})},fitsInCanvas:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          b){var c=b.getSize();return a.x>=c.width||0>a.x||a.y>=c.height||0>a.y?!1:!0}});l.Label.HTML=new k({Implements:l.Label.DOM,plotLabel:function(a,b,c){var a=b.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElement("div"),e=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";c.onCreateLabel(d,b);e.appendChild(d);this.labels[b.id]=d}this.placeLabel(d,b,c)}});l.Label.SVG=new k({Implements:l.Label.DOM,plotLabel:function(a,b,c){var a=b.id,d=this.getLabel(a);
    if(!d&&!(d=document.getElementById(a))){var d=document.createElementNS("http://www.w3.org/2000/svg","svg:text"),e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");d.appendChild(e);e=this.getLabelContainer();d.setAttribute("id",a);d.setAttribute("class","node");e.appendChild(d);c.onCreateLabel(d,b);this.labels[b.id]=d}this.placeLabel(d,b,c)}});var n=$jit.Layouts={},M={label:null,compute:function(a,b,c){this.initializeLabel(c);var d=this.label,e=d.style;a.eachNode(function(a){var b=
    a.getData("autoWidth"),c=a.getData("autoHeight");if(b||c){delete a.data.$width;delete a.data.$height;delete a.data.$dim;var j=a.getData("width"),k=a.getData("height");e.width=b?"auto":j+"px";e.height=c?"auto":k+"px";d.innerHTML=a.name;b=d.offsetWidth;c=d.offsetHeight;j=a.getData("type");-1===f.indexOf(["circle","square","triangle","star"],j)?(a.setData("width",b),a.setData("height",c)):(b=b>c?b:c,a.setData("width",b),a.setData("height",b),a.setData("dim",b))}})},initializeLabel:function(a){this.label||
(this.label=document.createElement("div"),document.body.appendChild(this.label));this.setLabelStyles(a)},setLabelStyles:function(){f.extend(this.label.style,{visibility:"hidden",position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};n.ForceDirected=new k({getOptions:function(){var a=this.canvas.getSize(),b=a.width,a=a.height,c=0;this.graph.eachNode(function(){c++});var d=b*a/c,e=Math.sqrt(d),f=this.config.levelDistance;return{width:b,height:a,tstart:0.1*b,nodef:function(a){return d/
    (a||1)},edgef:function(a){return e*(a-f)}}},compute:function(a,b){var c=f.splat(a||["current","start","end"]),d=this.getOptions();M.compute(this.graph,c,this.config);this.graph.computeLevels(this.root,0,"ignore");this.graph.eachNode(function(a){f.each(c,function(b){b=a.getPos(b);b.equals(o.KER)&&(b.x=d.width/5*(Math.random()-0.5),b.y=d.height/5*(Math.random()-0.5));a.disp={};f.each(c,function(b){a.disp[b]=A(0,0)})})});this.computePositions(c,d,b)},computePositions:function(a,b,c){var d=this.config.iterations,
    e=0,f=this;if(c)(function i(){for(var j=c.iter,k=0;k<j;k++)if(b.t=b.tstart,d&&(b.t*=1-e++/(d-1)),f.computePositionStep(a,b),d&&e>=d){c.onComplete();return}c.onStep(Math.round(100*(e/(d-1))));setTimeout(i,1)})();else for(;e<d;e++)b.t=b.tstart*(1-e/(d-1)),this.computePositionStep(a,b)},computePositionStep:function(a,b){var c=this.graph,d=Math.min,e=Math.max,g=A(0,0);c.eachNode(function(d){f.each(a,function(a){d.disp[a].x=0;d.disp[a].y=0});c.eachNode(function(c){c.id!=d.id&&f.each(a,function(a){var e=
    d.getPos(a),f=c.getPos(a);g.x=e.x-f.x;g.y=e.y-f.y;e=g.norm()||1;d.disp[a].$add(g.$scale(b.nodef(e)/e))})})});var h=!!c.getNode(this.root).visited;c.eachNode(function(c){c.eachAdjacency(function(d){var e=d.nodeTo;!!e.visited===h&&f.each(a,function(a){var d=c.getPos(a),f=e.getPos(a);g.x=d.x-f.x;g.y=d.y-f.y;d=g.norm()||1;c.disp[a].$add(g.$scale(-b.edgef(d)/d));e.disp[a].$add(g.$scale(-1))})});c.visited=!h});var i=b.t,j=b.width/2,k=b.height/2;c.eachNode(function(b){f.each(a,function(a){var c=b.disp[a],
    f=c.norm()||1,a=b.getPos(a);a.$add(A(c.x*d(Math.abs(c.x),i)/f,c.y*d(Math.abs(c.y),i)/f));a.x=d(j,e(-j,a.x));a.y=d(k,e(-k,a.y))})})}});$jit.ForceDirected=new k({Implements:[{construct:function(a){var b="array"==f.type(a),c=new l(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);if(b)for(var b=function(b){for(var d=0,e=a.length;d<e;d++)if(a[d].id==b)return a[d];return c.addNode({id:b,name:b})},d=0,e=a.length;d<e;d++){c.addNode(a[d]);var g=a[d].adjacencies;if(g)for(var h=0,i=g.length;h<
    i;h++){var j=g[h],k={};"string"!=typeof g[h]&&(k=f.merge(j.data,{}),j=j.nodeTo);c.addAdjacence(a[d],b(j),k)}}else(function(a,b){a.addNode(b);if(b.children)for(var c=0,d=b.children;c<d.length;c++)a.addAdjacence(b,d[c]),arguments.callee(a,d[c])})(c,a);return c},loadJSON:function(a,b){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(!0);this.graph=this.construct(a);this.root="array"!=f.type(a)?a.id:a[b?b:0].id},toJSON:function(a){if("tree"==(a||"tree"))var b={},b=function e(a){var b=
{};b.id=a.id;b.name=a.name;b.data=a.data;var c=[];a.eachSubnode(function(a){c.push(e(a))});b.children=c;return b}(this.graph.getNode(this.root));else{var b=[],c=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(a){var f={};f.id=a.id;f.name=a.name;f.data=a.data;var h=[];a.eachAdjacency(function(a){var b=a.nodeTo;if(!!b.visited===c){var e={};e.nodeTo=b.id;e.data=a.data;h.push(e)}});f.adjacencies=h;b.push(f);a.visited=!c})}return b}},w,n.ForceDirected],initialize:function(a){var b=
    $jit.ForceDirected,a=this.controller=this.config=f.merge(r("Canvas","Node","Edge","Fx","Tips","NodeStyles","Events","Navigation","Controller","Label"),{iterations:50,levelDistance:50},a);a.useCanvas?(this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label"):(a.background&&(a.background=f.merge({type:"Circles"},a.background)),this.canvas=new s(this,a),this.config.labelContainer=("string"==typeof a.injectInto?a.injectInto:a.injectInto.id)+"-label");this.graphOptions={klass:o,Node:{selected:!1,
    exist:!0,drawn:!0}};this.graph=new l(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);this.fx=new b.Plot(this,b);this.op=new b.Op(this);this.json=null;this.busy=!1;this.initializeExtras()},refresh:function(){this.compute();this.plot()},reposition:function(){this.compute("end")},computeIncremental:function(a){a=f.merge({iter:20,property:"end",onStep:f.empty,onComplete:f.empty},a||{});this.config.onBeforeCompute(this.graph.getNode(this.root));this.compute(a.property,
    a)},plot:function(){this.fx.plot()},animate:function(a){this.fx.animate(f.merge({modes:["linear"]},a||{}))}});$jit.ForceDirected.$extend=!0;n=$jit.ForceDirected;n.Op=new k({Implements:l.Op});n.Plot=new k({Implements:l.Plot});n.Label={};n.Label.Native=new k({Implements:l.Label.Native});n.Label.SVG=new k({Implements:l.Label.SVG,initialize:function(a){this.viz=a},placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.canvas,f=e.translateOffsetX,h=e.translateOffsetY,i=e.scaleOffsetX,j=e.scaleOffsetY,
    e=e.getSize(),f=Math.round(d.x*i+f+e.width/2),d=Math.round(d.y*j+h+e.height/2);a.setAttribute("x",f);a.setAttribute("y",d);c.onPlaceLabel(a,b)}});n.Label.HTML=new k({Implements:l.Label.HTML,initialize:function(a){this.viz=a},placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.canvas,f=e.translateOffsetX,h=e.translateOffsetY,i=e.scaleOffsetX,j=e.scaleOffsetY,k=e.getSize(),d={x:Math.round(d.x*i+f+k.width/2),y:Math.round(d.y*j+h+k.height/2)},f=a.style;f.left=d.x+"px";f.top=d.y+"px";f.display=
    this.fitsInCanvas(d,e)?"":"none";c.onPlaceLabel(a,b)}});n.Plot.NodeTypes=new k({none:{render:f.empty,contains:f.lambda(!1)},circle:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.circle.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.circle.contains(c,b,d)}},ellipse:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");this.nodeHelper.ellipse.render("fill",c,d,e,b)},contains:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");return this.nodeHelper.ellipse.contains(c,b,d,e)}},square:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.square.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.square.contains(c,b,d)}},rectangle:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");this.nodeHelper.rectangle.render("fill",c,d,e,b)},contains:function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");return this.nodeHelper.rectangle.contains(c,b,d,e)}},triangle:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.triangle.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.triangle.contains(c,b,d)}},star:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.star.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),
    d=a.getData("dim");return this.nodeHelper.star.contains(c,b,d)}}});n.Plot.EdgeTypes=new k({none:f.empty,line:{render:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0);this.edgeHelper.line.render(c,d,b)},contains:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0);return this.edgeHelper.line.contains(c,d,b,this.edge.epsilon)}},arrow:{render:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0),e=a.getData("dim"),f=a.data.$direction;this.edgeHelper.arrow.render(c,
    d,e,f&&1<f.length&&f[0]!=a.nodeFrom.id,b)},contains:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0);return this.edgeHelper.arrow.contains(c,d,b,this.edge.epsilon)}}})})();